import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

import './globals.css';

import { Open_Sans, Raleway } from "next/font/google";

const open_Sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open_Sans",
  weight: ["400", "500", "700"],
});

const raleway = Raleway({
  subsets: ["cyrillic"],
  variable: "--font-raleway",
  weight: ["700"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_Sans.className}>
        <section className="container">
          <Header />
          <main>
            {children}
          </main>
          <Footer/>
        </section>
      </body>
    </html>
  )
}
